# Test d'importation avec le script

In [1]:
from donnees_IDFM import donnees_archives
data1,data2=donnees_archives()

2015
2016
2017
2018
2019
2020
2021
2022

In [2]:
data1

,JOUR,CODE_STIF_TRNS,CODE_STIF_RES,CODE_STIF_ARRET,LIBELLE_ARRET,ID_REFA_LDA,CATEGORIE_TITRE,NB_VALD,annee,lda
0,01/01/2015,100,110,1,PORTE MAILLOT,71379,AMETHYSTE,117,2015,NaN
1,01/01/2015,100,110,1,PORTE MAILLOT,71379,AUTRE TITRE,37,2015,NaN
2,01/01/2015,100,110,1,PORTE MAILLOT,71379,FGT,172,2015,NaN
3,01/01/2015,100,110,1,PORTE MAILLOT,71379,IMAGINE R,605,2015,NaN
4,01/01/2015,100,110,1,PORTE MAILLOT,71379,NAVIGO,2039,2015,NaN
...,...,...,...,...,...,...,...,...,...,...
1105942,31/12/2022,810,802,905,VILLEPINTE,NaN,IMAGINE R,212,2022,73547.0
1105943,31/12/2022,810,802,905,VILLEPINTE,NaN,NAVIGO,614,2022,73547.0
1105944,31/12/2022,810,802,905,VILLEPINTE,NaN,NAVIGO JOUR,6,2022,73547.0
1105945,31/12/2022,810,802,905,VILLEPINTE,NaN,NON DEFINI,6,2022,73547.0
1105946,31/12/2022,810,802,905,VILLEPINTE,NaN,TST,202,2022,73547.0

In [3]:
data2

,CODE_STIF_TRNS,CODE_STIF_RES,CODE_STIF_ARRET,LIBELLE_ARRET,ID_REFA_LDA,CAT_JOUR,TRNC_HORR_60,pourc_validations,annee,lda
0,100,110,1,PORTE MAILLOT,71379,DIJFP,0H-1H,1.96,2015,NaN
1,100,110,1,PORTE MAILLOT,71379,DIJFP,10H-11H,4.01,2015,NaN
2,100,110,1,PORTE MAILLOT,71379,DIJFP,11H-12H,4.43,2015,NaN
3,100,110,1,PORTE MAILLOT,71379,DIJFP,12H-13H,5.36,2015,NaN
4,100,110,1,PORTE MAILLOT,71379,DIJFP,13H-14H,5.53,2015,NaN
...,...,...,...,...,...,...,...,...,...,...
85249,810,802,905,VILLEPINTE,NaN,SAVS,5H-6H,"4,25",2022,73547.0
85250,810,802,905,VILLEPINTE,NaN,SAVS,6H-7H,"7,22",2022,73547.0
85251,810,802,905,VILLEPINTE,NaN,SAVS,7H-8H,"6,79",2022,73547.0
85252,810,802,905,VILLEPINTE,NaN,SAVS,8H-9H,"6,39",2022,73547.0
85253,810,802,905,VILLEPINTE,NaN,SAVS,9H-10H,"5,84",2022,73547.0

Tout semble fonctionner correctement